---
# tasks file for prometheus
  - name: Create archives and prometheus directories
    file:
      name: "{{ item }}"
      state: directory
    with_items:
      - "{{ archives_dir }}"
      - "{{ prometheus_dir }}"
  - name: Download prometheus archive
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      dest: "{{ archives_dir }}"
  - include_tasks: "{{ ansible_facts.service_mgr }}.yml"
