- name: unarchive prometheus
  unarchive:
    src: "{{ archives_dir }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "{{ prometheus_dir }}"
    exclude: prometheus.yml
    remote_src: true
  notify: restart prometheus systemd
- name: Copy prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
  notify: restart prometheus systemd
- name: Create prometheus systemd file
  template:
    src: prometheus.systemd.j2
    dest: /etc/systemd/system/prometheus.service
  notify: systemd reload
- name: Start prometheus
  systemd:
    name: prometheus.service
    state: started
    enabled: true
